version: '3.8'
services:
  db:
    container_name: pg_container
    image: postgres
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: p4ssw0rd
      POSTGRES_DB: assistance_tickets
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: p4ssw0rd
    ports:
      - "5050:80"

  db-init:
    container_name: db-init
    image: postgres
    environment:
      PGPASSWORD: p4ssw0rd
    command: sh -c "psql -h db -U postgres -d assistance_tickets < dump.sql && echo 'Database initialized!'"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./db-init/dump.sql:/dump.sql
  
  app:
    container_name: g29-assistance-tickets-container
    image: pepaunz/ticket-assistance:latest
    depends_on:
      db-init:
        condition: service_completed_successfully
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/assistance_tickets
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=p4ssw0rd
      - SPRING_JPA_SHOW-SQL=true
      - SPRING_JPA_HIBERNATE_DDL-AUTO=validate
      - SPRING_JPA_DEFER-DATASOURCE-INITIALIZATION=true
      - SPRING_JPA_INIT_MODE=never
    restart: unless-stopped
    ports:
      - "8080:8080"

