version: '3.8'
services:
  db:
    container_name: pg_container
    image: postgres
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: p4ssw0rd
      POSTGRES_DB: assistance_tickets
    ports:
      - "5432:5432"
    volumes:
      - ./init-data/dump.sql:/docker-entrypoint-initdb.d/dump.sql
  app:
    container_name: g29-assistance-tickets-container
    image: pepaunz/assistance-tickets:v0.3
    depends_on:
      db:
        condition: service_healthy
      keycloak:
        condition: service_started
    env_file:
      - ./init-data/app.env
    restart: unless-stopped
    ports:
      - "8080:8080"
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:21.1.1
    command:
      - start-dev --import-realm --hostname-port=3000
    environment:
     - KEYCLOAK_ADMIN=admin
     - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "3000:8080"
    volumes:
      - ./init-data/SpringBootKeycloak-realm.json:/opt/keycloak/data/import/myrealm.json

