name: Run Tests

on:
  push:
  pull_request:
    branches: [ "master", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Grant execute permission
        run: |
          cd server
          chmod +x gradlew

      - name: Clean
        run: |
          cd server
          ./gradlew clean

      - name: Build
        run: |
          cd server
          ./gradlew build

      - name: Test
        run: |
          cd server
          ./gradlew test
